name: no_calls_after_null_example
description: An example for the custom rule
version: 0.1.0
publish_to: none

environment:
  sdk: '>=2.16.1 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

  custom_lint: ^0.0.12
  no_calls_after_null:
    path: ..
