name: no_calls_after_null
description: A custom lint rule that helps to avoid calls after assigning null
version: 0.1.0
publish_to: none

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  # we will use an analyzer for inspecting Dart files
  analyzer: ^6.3.0
  analyzer_plugin: ^0.11.3
  # custom_lint_builder will give us tools for writing lints
  custom_lint_builder: ^0.5.3

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
